name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "🐛 bug"
      - "🚑 hotfix"
  - title: "🔧 Maintenance"
    labels:
      - "🔧 technical-debt"
      - "🏗 infrastructure"
change-template: "- (#$NUMBER) $TITLE @$AUTHOR"
change-title-escapes: '\<*_&'
template: |
  ## Changes in v$RESOLVED_VERSION

  $CHANGES
