name: Issue Closed

on:
  issues:
    types: closed

jobs:
  update-release-notes:
    name: Update Release Notes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Generate changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issues: true
      - name: Create a release draft for a version tag
        id: create-release-draft
        uses: ecampidoglio/auto-release-draft@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print the URL of the release draft
        if: steps.create-release-draft.outputs.release-url != ''
        run: echo ${{ steps.create-release-draft.outputs.release-url }}
