name: Issue Closed

on:
  issues:
    types: closed

jobs:
  update-release-notes:
    name: Update Release Notes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Generate changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issues: true
