name: Master Updated

on:
  push:
    branches: master

jobs:
  master-updated:
    runs-on: ubuntu-latest

    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5.11.0
        with:
          publish: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
