name: Master Updated

on:
  push:
    branches: master

jobs:
  master-updated:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        id: github-tag-action
        uses: mathieudutour/github-tag-action@v4.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5.11.0
        with:
          version: ${{ steps.github-tag-action.outputs.new_tag }}
          publish: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
