name: Master Updated

on:
  push:
    branches: master

jobs:
  update-version:
    name: Update Version
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.github-tag-action.outputs.new_tag }}
      new_version: ${{ steps.github-tag-action.outputs.new_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        id: github-tag-action
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  create-draft-release:
    name: Create Draft Release
    runs-on: ubuntu-latest
    if: ${{ needs.update-version.outputs.new_tag != '' }}
    needs:
      - update-version
    env:
      NEW_TAG: ${{ needs.update-version.outputs.new_tag }}
      NEW_VERSION: ${{ needs.update-version.outputs.new_version }}
    steps:
      - name: Generate changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issues: true
      - name: Delete Draft Releases
        uses: hugo19941994/delete-draft-releases@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_TAG }}
          release_name: Release ${{ env.NEW_VERSION }}
          body: ${{ steps.tag_version.outputs.changelog }}
          draft: true
