name: Release

on:
  push:
    branches: trunk
    paths:
      - "**"
      - "!.github/**"
      - ".github/workflows/release.yml"
      - "!README.md"

env:
  ENVIRONMENT_NAME: production
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-test-deploy:
    name: Build, Test, Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        default:
          - package: api
            target: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Build & Test & Deploy
        working-directory: packages/${{ matrix.package }}
        run: |
          DOCKER_BUILDKIT=1 docker build \
            -t agilelytics/${{ matrix.package }}:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --build-arg ENVIRONMENT_NAME=${{ env.ENVIRONMENT_NAME }} \
            --build-arg AWS_DEFAULT_REGION=${{ env.AWS_DEFAULT_REGION }} \
            --build-arg AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }} \
            --build-arg AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }} \
            --target ${{ matrix.target }} \
            .
