name: web-deploy

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/web.deploy.yml"
      - "web/**"

env:
  NODE_VERSION: "12.x"
  AWS_REGION: "ca-central-1"
  WEBSITE_NAME: "asana.albon.me"

defaults:
  run:
    working-directory: web

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --immutable
      - run: yarn test
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: asana.agile.web-build
          path: web/build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: actions/download-artifact@master
        with:
          name: asana.agile.web-build
          path: web/build
      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./build/ s3://${{ env.WEBSITE_NAME }} --delete --acl public-read
